# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

f = [1, 2]
even_f = []

for i in range(90):
    sequence = f[i]+f[i+1]
    if sequence < 4000000:
        f.append(sequence)
    else:
        break

for x in f:
    if x % 2 == 0:
        even_f.append(x)

print(f)
print(sum(f))
print(even_f)
print(sum(even_f))
